openapi: 3.0.1
info:
  title: Shiksha Grades API
  version: 1.0.0
paths:
  /api/assignments/{assignmentId}/grades:
    post:
      summary: Publish grades for an assignment
      parameters:
        - name: assignmentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  student_id:
                    type: string
                  score:
                    type: number
                  feedback:
                    type: string
      responses:
        '200':
          description: OK
components: {}
